---
title: "CSS-360-Final-Project"
author: "Somin Park"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)

options(scipen=999)
```

## ATUS Data
Reference for data descriptions: https://www.bls.gov/tus/data/datafiles-0324.htm

Data files google drive: https://drive.google.com/drive/folders/1RYAvKluPasULGk68OPw5b8FkcoFuPK16?usp=drive_link

```{r import}
resp <- read.delim('atusresp-0324/atusresp_0324.dat', sep=",")
rost <- read.delim('atusrost-0324/atusrost_0324.dat', sep=",")
activity <- read.delim('atusact-0324/atusact_0324.dat', sep=",")
```

```{r cleaning columns}
rost <- rost |> filter(TULINENO == 1)

rost <- rost |> select(TUCASEID, TEAGE, TESEX)
rost <- rost |> rename(id = TUCASEID,
               age = TEAGE,
               gender = TESEX)

resp <- resp |> select(TUCASEID, TUDIARYDATE, TUYEAR, TUMONTH, TUDIARYDAY, TELFS, TESCHENR, TRTALONE)
resp <- resp |> rename(id = TUCASEID,
               date = TUDIARYDATE,
               year = TUYEAR,
               month = TUMONTH,
               day_of_wk = TUDIARYDAY,
               work_status = TELFS,
               student_status = TESCHENR,
               nonwork_time_alone = TRTALONE
               )

activity <- activity |> select(TUCASEID, TUACTIVITY_N, TRCODEP, TRTIER1P, TRTIER2P, TEWHERE, TUACTDUR, TUSTARTTIM, TUSTOPTIME)
activity <- activity |> rename(id = TUCASEID,
                   activity_line_num = TUACTIVITY_N,
                   activity = TRCODEP,
                   first_two_digits_activity = TRTIER1P,
                   first_four_digits_activity = TRTIER2P,
                   location = TEWHERE,
                   duration = TUACTDUR,
                   start_time = TUSTARTTIM,
                   stop_time = TUSTOPTIME
                   )
```

```{r merge}
resp <- left_join(resp, rost, by = "id") |> relocate(c(age, gender), .after = id) # merge resp and roster data

activity <- left_join(activity, resp, by = "id") #merge activity and resp data
```

```{r cleaning1}
activity$gender <- factor(activity$gender,
                               levels = c(1, 2),        
                               labels = c("M", "F"))

activity <- activity |> mutate(date = ymd(date))
activity$day_of_wk <- factor(activity$day_of_wk,
                             levels = c(1:7),
                             labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))

```

```{r cleaning2}
activity_2020_24 <- activity |> filter(year %in% 2020:2024) |> filter(first_two_digits_activity %in% c(11, 12, 13, 18)) #filter from 2020 to 2024 & leisure-related activities

activity_2020_24 <- activity_2020_24 |> mutate(first_two_digits_classification = factor(activity_2020_24$first_two_digits_activity,
                             levels = c(11, 12, 13, 18),
                             labels = c("Eating and Drinking", "Socializing, Relaxing, and Leisure", "Sports, Exercise, & Recreation", "Traveling"))) |> relocate(first_two_digits_classification, .after = first_two_digits_activity) # re-coding first two digits

activity_2020_24 |> count(first_four_digits_activity)

activity_2020_24 <- activity_2020_24 |> filter(first_four_digits_activity %in% c(1101, 1201, 1202, 1203, 1204, 1301, 1302, 1801, 1802, 1811, 1812, 1813)) # filtering leisure related activities

activity_2020_24 <- activity_2020_24 |> mutate(first_four_digits_classifications = recode(first_four_digits_activity,
                           `1101` = "Eating and Drinking",
                           `1201` = "Socializing and Communicating",
                           `1202` = "Attending or Hosting Social Events",
                           `1203` = "Relaxing and Leisure",
                           `1204` = "Arts and Entertainment",
                           `1301` = "Participating in Sports, Exercise, and Recreation",
                           `1302` = "Attending Sports/Recreational Events",
                           `1801` = "Traveling",
                           `1802` = "Traveling",
                           `1811` = "Traveling",
                           `1812` = "Traveling",
                           `1813` = "Traveling")) |> 
  relocate(first_four_digits_classifications, .after = first_four_digits_activity) # re-coding

activity_2020_24 |> count(first_four_digits_classifications)
# key activity code: 12, 13 => need to recode them in detail.
```

```{r cleaning3}
activity_2020_24 <- activity_2020_24 |>
  mutate(activity_detail = recode(activity,
                           `110101` = "Eating and Drinking",
                           `120101` = "Socializing and Communicating with others",
                           `120201` = "Attending or Hosting Social Events",
                           `120301` = "Relaxing, thinking",
                           `120303` = "Television and movies",
                           `120304` = "Television and movies",
                           `120305` = "Listening to the radio",
                           `120306` = "Listening to/playing music",
                           `120307` = "Playing games",
                           `120309` = "Arts and crafts as a hobby",
                           `120310` = "Collecting as a hobby",
                           `120312` = "Reading for personal interest",
                           `120313` = "Writing for personal interest",
                           `120401` = "Attending performing arts",
                           `120402` = "Attending museums",
                           `120403` = "Attending movies/film",
                           `120404` = "Attending gambling establishments",
                           `130101` = "Doing aerobics",
                           `130102` = "Playing baseball",
                           `130103` = "Playing basketball",
                           `130104` = "Biking",
                           `130105` = "Playing billiards",
                           `130106` = "Boating",
                           `130107` = "Bowling",
                           `130108` = "Climbing, spelunking, caving",
                           `130109` = "Dancing",
                           `130110` = "Participating in equestrian sports",
                           `130111` = "Fencing",
                           `130112` = "Fishing",
                           `130113` = "Playing football",
                           `130115` = "Doing gymnastics",
                           `130116` = "Hiking",
                           `130117` = "Playing hockey",
                           `130119` = "Participating in martial arts",
                           `130120` = "Playing racquet sports",
                           
                           `130122` = "Roller skating, inline skating, skateboarding",
                           `130224` = "Running",
                           `130231` = "Walking",
                           `180101` = "Travel related to personal care",
                           `180280` = "Travel related to household activities",
                           `181201` = "Travel related to socializing and communicating",
                           .default = NA_character_)) |>
  relocate(activity_detail, .after = activity) # re-coding
```

```{r cleaning4}
# location 
activity_2020_24 <- activity_2020_24 |> mutate(location_detail = factor(activity_2020_24$location,
                             levels = c(1:5, 7:11, 14:17, 31),
                             labels = c("Respondent's home or yard",
                                        "Respondent's workplace",
                                        "Someone else's home",
                                        "Restaurant or bar",
                                        "Place of worship",
                                        "Other store/mall",
                                        "School",
                                        "Outdoors away from home",
                                        "Library",
                                        "Tourist spots/other place",
                                        "Walking",
                                        "Bus",
                                        "Subway/train",
                                        "Bicycle",
                                        "Gym/health club"
                                        ))) |> 
  relocate(location_detail, .after = location) # re-coding locations

activity_2020_24 |> group_by(location_detail) |> summarize(n())

#remove NA from location_detail & activity_detail
##activity_2020_24 <- activity_2020_24 |> na.omit(location_detail)
##activity_2020_24 <- activity_2020_24 |> na.omit(activity_detail)

# student status 
activity_2020_24$student_status <- factor(activity_2020_24$student_status,
                               levels = c(1, 2),        
                               labels = c("Student", "Non-student"))

# work status
activity_2020_24$work_status <- factor(activity_2020_24$work_status,
                               levels = c(1, 2, 3, 4, 5),        
                               labels = c("Employed", "Employed", "Unemployed", "Unemployed", "Not in labor force"))

# age categorization
activity_2020_24 <- activity_2020_24 |> 
  mutate(age_group = cut(age, 
                         breaks = c(-Inf, 18, 25, 45, 60, Inf), 
                         labels = c("under 18", "18-24", "25-44", "45-59", "60 or older"),
                         right = FALSE)) |>
  relocate(age_group, .before = age)

activity_2020_24 |> group_by(age_group) |> summarise(n())

activity_2020_24 <- activity_2020_24 |> 
  mutate(wkday_wkend = case_when(
    day_of_wk %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") ~ "weekdays",
    day_of_wk %in% c("Saturday", "Sunday") ~ "weekends")) |> 
  relocate(wkday_wkend, .before = day_of_wk)

# morning / afternoon / night activities
activity_2020_24 <- activity_2020_24 |> 
  mutate(start_hour = hour(hms(start_time)),
         time_slot = case_when(
           start_hour >= 5 & start_hour < 12 ~ "morning",
           start_hour >= 12 & start_hour < 18 ~ "afternoon",
           TRUE ~ "night"
           )
         ) |> 
  mutate(time_slot = factor(time_slot, levels = c("morning", "afternoon", "night"))) |>
  relocate(c(start_hour, time_slot), .after = start_time)
```


```{r cleaning5}
# convert min to hours (nonwork time & duration & cum_duration)
activity_2020_24 <- activity_2020_24 |>
  mutate(nonwork_time_hours = round(nonwork_time_alone / 60, 1)) |>
  relocate(nonwork_time_hours, .after = nonwork_time_alone)

activity_2020_24 <- activity_2020_24 |>
  mutate(duration_hours = round(duration / 60, 1)) |>
  relocate(duration_hours, .after = duration)

# added a season column
activity_2020_24 <- activity_2020_24 |>
  mutate(season = case_when(
  month %in% c(12, 1, 2) ~ "winter",
  month %in% c(3, 4, 5) ~ "spring",
  month %in% c(6, 7, 8) ~ "summer",
  month %in% c(9, 10, 11) ~ "fall",
  TRUE ~ NA_character_
  )) |> 
  relocate(season, .before = month)
```

```{r observation1}
activity_2020_24 |>
  group_by(first_four_digits_classifications, activity_detail) |> count(sort = T) |> arrange(desc(n))

# Top activities
activity_2020_24 |>
  filter(!is.na(first_two_digits_classification)) |>
  count(first_two_digits_classification, sort = T)

activity_2020_24 |>
  filter(!is.na(first_four_digits_classifications)) |>
  count(first_four_digits_classifications, sort = T)

# top 10 activities
activity_2020_24 |>
  filter(!is.na(activity_detail)) |>
  count(activity_detail, sort = T) |>
  head(10) |> 
  ggplot(aes(x = reorder(activity_detail, n), y = n)) +
  geom_col(fill = "skyblue", width = 0.7) +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Top 10 Most Frequent Activities",
    x = "",
    y = "Frequency (Count)"
  )

# most frequent locations
activity_2020_24 |> filter(!is.na(location_detail)) |> group_by(location_detail) |> count() |> arrange(desc(n))

# top 3 activities for each location
activity_2020_24 |> 
  filter(!is.na(location_detail) & !is.na(activity_detail)) |>
  group_by(location_detail, activity_detail) |>
  summarise(count = n(), .groups = 'drop') |>
  group_by(location_detail) |> 
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 3)
```

```{r observation2}
# top 5 activities and duration for each time slot based on student status
activity_2020_24 |> filter(student_status == "Student" & !is.na(time_slot) & !is.na(activity_detail)) |>
  group_by(time_slot, activity_detail) |> 
  summarise(count = n(),
            avg_duration = mean(duration_hours),
            avg_nonwork_time_hours = mean(nonwork_time_hours),
            prop_avg_duration = mean(duration_hours) / mean(nonwork_time_hours),
            .groups = 'drop') |>
  group_by(time_slot) |>
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5)

activity_2020_24 |> filter(student_status == "Non-student" & !is.na(time_slot) & !is.na(activity_detail)) |>
  group_by(time_slot, activity_detail) |> 
  summarise(count = n(),
            avg_duration = mean(duration_hours),
            avg_nonwork_time_hours = mean(nonwork_time_hours),
            prop_avg_duration = mean(duration_hours) / mean(nonwork_time_hours),
            .groups = 'drop') |>
  group_by(time_slot) |>
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5)

# proportion of activity duration based on student status
prop_duration_non_student <- activity_2020_24 |> filter(student_status == "Non-student" & !is.na(student_status) & !is.na(activity_detail)) |>
  group_by(student_status, activity_detail) |> 
  summarise(count = n(),
            avg_duration = mean(duration_hours),
            avg_nonwork_time_hours = mean(nonwork_time_hours),
            prop_avg_duration = mean(duration_hours) / mean(nonwork_time_hours),
            .groups = 'drop') |>
  group_by(student_status) |> 
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5) |> arrange(desc(prop_avg_duration))

prop_duration_student <- activity_2020_24 |> filter(student_status == "Yes" & !is.na(student_status) & !is.na(activity_detail)) |>
  group_by(student_status, activity_detail) |> 
  summarise(count = n(),
            avg_duration = mean(duration_hours),
            avg_nonwork_time_hours = mean(nonwork_time_hours),
            prop_avg_duration = mean(duration_hours) / mean(nonwork_time_hours),
            .groups = 'drop') |>
  group_by(student_status) |> 
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5) |> arrange(desc(prop_avg_duration))

bind <- bind_rows(prop_duration_student, prop_duration_non_student)
bind
```

```{r observation3}
# Top 5 activities by age group
activity_2020_24 |> 
  filter(!is.na(age_group) & !is.na(activity_detail)) |>
  group_by(age_group, activity_detail) |>
  summarise(count = n(), .groups = 'drop') |>
  group_by(age_group) |> 
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5)

# Activity proportion by age group
activity_2020_24 |>
  filter(!is.na(age_group) & !is.na(first_four_digits_classifications)) |>
  count(age_group, first_four_digits_classifications) |>
  filter(n > 300) |>
  group_by(age_group) |>
  mutate(prop = n / sum(n)) |> 
  ggplot(aes(x = age_group, y = prop, fill = first_four_digits_classifications)) +
  geom_col(position = "fill", width = 0.7) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(
    title = "Activity Proportion by Age Group",
    x = "Age Group",
    y = "Proportion",
    fill = "Activity Category"
  )

# Ppl usually do what in Tourist spots/other places
activity_2020_24 |> filter(location_detail == "Tourist spots/other place" & !is.na(activity_detail)) |> group_by(activity_detail) |> count() |> arrange(desc(n))
```

```{r visualization}
# activities by age group
activity_2020_24 |> 
  filter(!is.na(age_group) & !is.na(activity_detail)) |>
  group_by(age_group, activity_detail) |>
  summarise(count = n(), .groups = 'drop') |>
  group_by(age_group) |> 
  arrange(desc(count), .by_group = TRUE) |>
  slice_head(n = 5)

activity_2020_24 |>
  filter(!is.na(student_status) & !is.na(activity_detail) & !is.na(work_status)) |> 
  group_by(activity_detail) |> 
  summarise(count = n(), .groups = 'drop') |> 
  arrange(desc(count)) |> 
  slice_head(n = 10)
                             
```

```{r}
write_csv(activity_2020_24, "app/data/atus_activity_2020_24.csv")
```

