---
title: "Meetup_data"
author: "Radhika Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r import}
#I used chromote bc Meetup.com mostly rendered w/ JavaScript and 
#this was the best way I could scrape the website. Rvest is also there
#for the HTML but chromote runs a real headless Chrome browser within 
#R.
library(chromote)
library(rvest)
library(dplyr)
library(stringr)

#Here a new chromote session runs 
#watched this video for help w/the package-> https://www.youtube.com/watch?v=30AOpjLeOyI
b <- ChromoteSession$new()

search_url <- "https://www.meetup.com/find/?keywords=art&location=us--nj--New+Brunswick&source=EVENTS"
#Here is where chromote loads the meetup.com URL in a headless/remote
#browser b/c it need to render the JavaScript content that rvest can't.
b$Page$navigate(search_url)
Sys.sleep(5)
          

html <- b$Runtime$evaluate("document.documentElement.outerHTML")$result$value
page <- read_html(html)
```

```{r name}
#Getting the event name
event_name <- page %>% 
  html_nodes("h3") %>% 
  html_text(trim = TRUE)
```

```{r links}
#Getting clickable links to each indiviual event
links <- page %>% 
  html_nodes("h3 a") %>% 
  html_attr("href")
#paste0() used to combine the domain w/the relative path
event_links <- paste0("https://www.meetup.com", links)
event_links <- unique(event_links)

event_links <- event_links[grepl("/events/", event_links)]
#event_links <- paste0("https://www.meetup.com", event_links)
#event_links <- unique(event_links)
cat("Found", length(event_links), "event links\n")
#event_details <- lapply(event_links)

#working on getting fixing the links bc they were working yesterday
#UGH THIS ISNT WORKING UGHHHHGHGHGHGHGHGHGHGH
```

```{r groups & date w/time}
#Getting group name, organizer of event
groups <- page %>% 
  html_nodes("h3 + div") %>% 
  html_text(trim = TRUE)

#Getting date of event w/time
#Working on getting year to see stats patterns b/w upcoming events
#and past events.
dates <- page %>% 
  html_nodes("time") %>% 
  html_text(trim = TRUE)
```

```{r}
#Determing longest vector b/w scraper columns of data sicne data.frame
#can't combine different length vectors.
max_len <- max(length(event_name), length(event_links), length(groups), length(dates))

pad <- function(x, n) { length(x) <- n; x }

event_name <- pad(event_name, max_len)
event_links <- pad(event_links, max_len)
groups <- pad(groups, max_len)
dates <- pad(dates, max_len)

events_df <- data.frame(
  event_name = event_name,
  group = groups,
  date = dates,
  link = event_links,
  stringsAsFactors = FALSE
)

events_df
```